import Head from 'next/head'
import Banner from"../src/components/Banner/Banner"
import Navbar from '@/src/components/Navbar/Navbar'
import Footer from '@/src/components/Footer/Footer'


export default function Home() {
  return (
    <>
    <div className="m-auto h-screen" >
      <Head>
        <title>"redapple"-Your trusteed partner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Banner/>
     <Navbar/>
     <Footer/>
     </div>
    </>
  )
}
